services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr-arr
    environment:
      - LOG_LEVEL=info
    network_mode: service:gluetun
    depends_on:
      - gluetun
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${MULLVAD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${MULLVAD_ADDRESS}
      - SERVER_COUNTRIES=Romania,Poland,Czech Republic
      - FIREWALL_VPN_INPUT_PORTS=6881
      - DOT_IPV6=off
      - DOT=off
      - BLOCK_MALICIOUS=off
      - BLOCK_ADS=off
      - DNS_ADDRESS=1.1.1.1
      - FIREWALL_OUTBOUND_SUBNETS=172.19.0.0/16
      - FIREWALL_INPUT_PORTS=8080,9696,8191,6881,5299
      - UPDATER_PERIOD=24h
    ports:
      - 8080:8080 # qBittorrent
      - 6881:6881/tcp
      - 6881:6881/udp
      - 9696:9696 # Prowlarr
      - 8191:8191 # FlareSolverr
      - 5299:5299 # LazyLibrarian
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
    volumes:
      - /mnt/ssd/config/qbittorrent:/config
      - /mnt/ssd/downloads:/downloads
    network_mode: service:gluetun
    depends_on:
      - gluetun
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/config/prowlarr:/config
    network_mode: service:gluetun
    depends_on:
      - gluetun
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/config/radarr:/config
      - /mnt/ssd/media/movies:/movies
      - /mnt/ssd/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/config/sonarr:/config
      - /mnt/ssd/media/series:/tv
      - /mnt/ssd/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/config/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  # ─── BOEKEN ─────────────────────────────────────────────────────

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /mnt/ssd/config/calibre-web:/config
      - /mnt/ssd/media/books/ebooks:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  # ─── DASHBOARD ──────────────────────────────────────────────────
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=100.111.218.120:3000
    volumes:
      - /mnt/ssd/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/ssd:/mnt/ssd:ro
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - FB_USERNAME=admin
      - FB_PASSWORD=Huursignal123!
    volumes:
      - /mnt/ssd:/srv
      - /mnt/ssd/config/filebrowser:/database
      - /mnt/ssd/config/filebrowser:/config
    ports:
      - 8085:80
    restart: unless-stopped

  #--- STATS --------------------
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    ports:
      - "61208:61208"
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
